@startuml

database "Workspace" as W
database "Index" as I
database "Local Repository" as LR
database "Remote Repository" as RR
Actor "Reviewer" as R
database "Upstream Repository" as UR

alt Clone remote(forked) repository to local
    RR -> W : git clone --branch <branch> <git ssh url> <local directory>
end

alt Local to project branch
    UR -> W : git fetch upstream <branch> 
    UR <- W : git merge upstream/<branch> 
    W -> I : git add .
    I -> LR : git commit -m <commit message>
    LR -> RR : git push
    RR -> R : pull request
    R -> UR : merge pull request
end

alt Get new upstream branch to local and push to remote(forked) 
    UR -> W : git fetch upstream <new branch>
    W -> W : git checkout -b <new branch> upstream/<new branch>
    W -> RR : git push -u origin <new branch>
end

@enduml
